name: Build Executables

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    env:
      MAIN_SPEC_FILE: 'main.spec'  # Define the path to your main.spec file here
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.4
      - name: Install esptool
        run: |
          pip install esptool
        working-directory: ./
      - name: Create virtual environment
        run: |
          python -m venv venv
      - name: Activate virtual environment (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          venv\Scripts\activate.bat
      - name: Activate virtual environment (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          source venv/bin/activate
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./
      - name: Install PyInstaller
        run: |
          pip install pyinstaller
        working-directory: ./
      - name: Build executable
        run: |
          pyinstaller ${{ env.MAIN_SPEC_FILE }}
        working-directory: ./
      - name: Create ZIP archive
        run: |
          zip -r ESPFlasher-${{ matrix.os }}.zip dist/ESPFlasher
      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: ESPFlasher-${{ matrix.os }}
          path: ESPFlasher-${{ matrix.os }}.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Assets
        uses: actions/download-artifact@v3
        with:
          path: assets
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            assets/ESPFlasher-windows-latest/ESPFlasher-windows-latest.zip
            assets/ESPFlasher-ubuntu-latest/ESPFlasher-ubuntu-latest.zip
            assets/ESPFlasher-macos-latest/ESPFlasher-macos-latest.zip
          body: This is the release for ${{ github.ref }}
          name: Release ${{ github.ref }}