name: Build Executables

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    env:
      MAIN_SPEC_FILE: 'main.spec'  # Define the path to your main.spec file here
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.4
      - name: Install esptool
        run: |
          pip install esptool
        working-directory: ./
      - name: Create virtual environment
        run: |
          python -m venv venv
      - name: Activate virtual environment (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          venv\Scripts\activate.bat
      - name: Activate virtual environment (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          source venv/bin/activate
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./
      - name: Install PyInstaller
        run: |
          pip install pyinstaller
        working-directory: ./
      - name: Build executable
        run: |
          pyinstaller ${{ env.MAIN_SPEC_FILE }}
        working-directory: ./
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: This is the release for ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          assets=()
          for asset in ./dist/*; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release edit "${assets[@]}" -m "" "$tag_name"